version: '2'
services:
  web:
    build: 
      context: front-end
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./front-end:/penelope
    ports:
      - "3000:3000"
    links:
      - db:db
      - redis:redis

